/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tela;

import DAO.QuartosDAO;
import classes.Quartos;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rafae
 */
public final class Quarto extends javax.swing.JFrame {

    private Login login;
    private Cadastro cadastro;
    private Reserva reserva;

    public Quarto(Reserva reserva) throws SQLException {
        this.reserva = reserva;
        initComponents();
        preencherTabela();

    }

    public Quarto(Cadastro cadastro) {
        this.cadastro = cadastro;
        initComponents();
    }

    /**
     * Creates new form Reserva
     */
    public Quarto(Login login) {
        this.login = login;
        initComponents();
    }

    public Quarto() throws SQLException {
        initComponents();
        preencherTabela();
    }

    public void preencherTabela() throws SQLException {
        DefaultTableModel modelo = (DefaultTableModel) tbQuartos.getModel();
        modelo.setNumRows(0);
        QuartosDAO qdao = new QuartosDAO();

        for (Quartos q : qdao.lerBanco()) {
            modelo.addRow(new Object[]{
                q.getNumQuartos(),
                q.getDescricao(),
                q.getStatus(),
                q.getPreco(),
                q.getData(),});
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbQuartos = new javax.swing.JTable();
        jBReservar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quartos");

        jPanel1.setBackground(new java.awt.Color(217, 250, 198));

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 28)); // NOI18N
        jLabel1.setText("Quartos");

        tbQuartos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tbQuartos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"100", "Quarto Solterio ", "disponível ", "R$ 89.99", "13/10/24-16/10/24"},
                {"101", "Quarto casal", "disponível ", "R$ 139.99", "02/10/24-15/10/24"},
                {"200", "Quarto vip solteiro", "disponível ", "R$ 109.99", "1/10/24-14/10/24"},
                {"201", "Quarto vip casal", "disponível ", "R$ 209.99", "10/10/24-13/10/24"},
                {"300", "Cobertura vip", "disponível ", "R$ 900.00", "09/10/24-12/10/24"}
            },
            new String [] {
                "Número do Quarto", "Descrição", "Status", "Valor por dia", "Data"
            }
        ));
        tbQuartos.setColumnSelectionAllowed(true);
        tbQuartos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbQuartos.setFillsViewportHeight(true);
        tbQuartos.setMaximumSize(new java.awt.Dimension(2147483647, 150));
        tbQuartos.setName(""); // NOI18N
        tbQuartos.setRowHeight(30);
        tbQuartos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbQuartos.setShowGrid(true);
        tbQuartos.setSurrendersFocusOnKeystroke(true);
        tbQuartos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbQuartosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbQuartos);
        tbQuartos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jBReservar.setBackground(new java.awt.Color(153, 153, 255));
        jBReservar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jBReservar.setForeground(new java.awt.Color(0, 51, 153));
        jBReservar.setText("Reservar");
        jBReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBReservarActionPerformed(evt);
            }
        });

        jBCancelar.setBackground(new java.awt.Color(153, 153, 255));
        jBCancelar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jBCancelar.setForeground(new java.awt.Color(0, 51, 153));
        jBCancelar.setText("Cancelar Reserva");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Hotel Montanha Serena");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(397, 397, 397)
                        .addComponent(jLabel1)
                        .addGap(0, 355, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(17, 17, 17))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jBReservar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBCancelar)
                .addGap(61, 61, 61))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBReservar)
                    .addComponent(jBCancelar))
                .addGap(83, 83, 83))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        // TODO add your handling code here:

        Cancela frameCancelar = new Cancela(this.reserva);
        setVisible(false);
        frameCancelar.setVisible(true);

    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jBReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBReservarActionPerformed
        // TODO add your handling code here:

        tbQuartos.getSelectedRow();
        Reserva reserva = new Reserva(this);
        setVisible(false);
        reserva.setVisible(true);


    }//GEN-LAST:event_jBReservarActionPerformed

    private void tbQuartosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbQuartosMouseClicked

    }//GEN-LAST:event_tbQuartosMouseClicked

    /**
     * @param args the command line argumentst
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quarto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quarto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quarto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quarto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new Quarto().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Quarto.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBReservar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tbQuartos;
    // End of variables declaration//GEN-END:variables
}
